### ISSUE TITLE
Config missing

### ISSUE THREAD

**Issue by killua-eu** [oidcphp/example-slim#1]
Hi,

when evaluating oidc-core usability against keycloak, I noticed that
https://github.com/oidcphp/example-slim/blob/328f64b0192f65cd1011104a18e88f8760e6754d/bootstrap/app.php#L33
is missing. I also didnt find the config structure documented anywhere. Looking into the code, I found that this is supposed to be generated by running `php bin/console.php discover` from the shell, but this exits with an error

```
PHP Fatal error:  Uncaught Error: Call to undefined method OpenIDConnect\Issuer::create() in /srv/varwwwhtml/glued-skeleton/public/f/example-slim/app/Commands/Discover.php:37
Stack trace:
#0 /srv/varwwwhtml/glued-skeleton/public/f/example-slim/app/Commands/Discover.php(29): App\Commands\Discover->discoverGoogle()
#1 /srv/varwwwhtml/glued-skeleton/public/f/example-slim/vendor/symfony/console/Command/Command.php(255): App\Commands\Discover->execute()
#2 /srv/varwwwhtml/glued-skeleton/public/f/example-slim/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#3 /srv/varwwwhtml/glued-skeleton/public/f/example-slim/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#4 /srv/varwwwhtml/glued-skeleton/public/f/example-slim/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#5 /srv/varwwwhtml/glued-skeleton/public/f/example-slim/bin/console.php(8): Symfony\Component\Console\Application->run()
#6 {main}
  th in /srv/varwwwhtml/glued-skeleton/public/f/example-slim/app/Commands/Discover.php on line 37
```

even though the class is there. The namespacing seems all right, but it doesnt work. Installed with:

```
git clone https://github.com/oidcphp/example-slim
cd example-slim
composer update
```

**Comment by MilesChou** [comment]
Fixed.
